version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3.11.10-management-alpine
    container_name: "cims-rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq

networks:
  rabbitmq:
    driver: bridge
