version: "3.9"
name: "cims"

services:
  # cims:
  #   image: 123pedrosilva123/cims-bot:1.1.0-alpha
  #   container_name: cims-bot
  #   environment:
  #     - CIMS_BOT_DISCORD_TOKEN=token
  #     - CIMS_BOT_RABBIT_USERNAME=guest
  #     - CIMS_BOT_RABBIT_PASSWORD=guest
  #     - CIMS_BOT_RABBIT_HOST=rabbitmq
  #     - CIMS_BOT_REDIS_HOST=redis
  #     - CIMS_BOT_REDIS_PORT=6379
  #   restart: always
  #   depends_on:
  #     - rabbitmq
  #     - redis

  rabbitmq:
    image: rabbitmq:3.11.10-management-alpine
    container_name: cims-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  redis:
    image: redis:7.2-rc-bullseye
    container_name: cims-redis
    ports:
      - 6379:6379
    restart: always
